[project]
name = "agenticai-openai-llm-call"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Debarupa", email = "royc.debarupa@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.0",
    "langchain-openai>=1.6.1",
    "openai>=3.8.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
]

[project.scripts]
agenticai-openai-llm-call = "agenticai_openai_llm_call:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
